const https = require('https');
const fs = require('fs');
const path = require('path');

// Next.js standalone server handles the logic
// This file is generated by 'next build'
const { createServer } = require('./.next/standalone/server');

const options = {
  key: fs.readFileSync('/etc/tls/tls.key'),
  cert: fs.readFileSync('/etc/tls/tls.crt'),
};

const port = 8443;

// The 'createServer' from standalone mode returns a standard Node listener
const server = https.createServer(options, createServer);

server.listen(port, (err) => {
  if (err) {
    console.error('Failed to start server', err);
    process.exit(1);
  }
  console.log(`> Listening on https://localhost:${port}`);
});